### ISSUE TITLE
Py Error

### ISSUE THREAD

**Issue by REAPXR666** [virajmane/IPLogger#2]
What python version and how to get it working on REPL

**Comment by virajmane** [comment]
You can try python-3.8.5 and you need to get credentials from firebase realtime database. For REPL you can use secrets to hide the credentials and import them into the code. At some places the URL is hard coded so, you need to change those to your repl's URL. To get started on repl, just clone this repository and it will automatically handle all the dependencies.

**Comment by REAPXR666** [comment]
Can you possibly put a working GitHub version + link so I can Fork it from Repl, would really appreciate it!
> repository

**Comment by REAPXR666** [comment]
https://URLShortner.virajman3.repl.co
For example, use that and make it public for us to use.

**Comment by virajmane** [comment]
Here is a working version, I have made it simple by just keeping the core functionality and removing the firebase credentials now you can integrate it with any database that you like
Repo: https://replit.com/@virajman3/iplogger
URL: https://iplogger.virajman3.repl.co
