### ISSUE TITLE
REPL

### ISSUE THREAD

**Issue by REAPXR666** [virajmane/IPLogger#3]
Please make a working version on repl and send link to us so we can fork it and use it on repl,
Since the python on it just throws errors.
Thanks

**Comment by virajmane** [comment]
Here is a working version, I have made it simple by just keeping the core functionality and removing the firebase credentials now you can integrate it with any database that you like
Repo: https://replit.com/@virajman3/iplogger
URL: https://iplogger.virajman3.repl.co
